/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea.pkg4.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author gilbe
 */
public class ProcesarDatosGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProcesarDatosGUI.class.getName());

    /**
     * Creates new form ProcesarDatosGUI
     */
    public ProcesarDatosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCuatri = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnResetear = new javax.swing.JButton();
        btnCapturar = new javax.swing.JButton();
        btnPresentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Procesador de datos ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 18, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese la informacion pedida");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Matricula:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cuatrimestre:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        txtCuatri.setBackground(new java.awt.Color(255, 255, 255));
        txtCuatri.setForeground(new java.awt.Color(0, 0, 0));
        txtCuatri.addActionListener(this::txtCuatriActionPerformed);
        jPanel2.add(txtCuatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 160));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResetear.setBackground(new java.awt.Color(255, 255, 255));
        btnResetear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnResetear.setForeground(new java.awt.Color(0, 0, 0));
        btnResetear.setText("Resetear");
        btnResetear.addActionListener(this::btnResetearActionPerformed);
        jPanel3.add(btnResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btnCapturar.setBackground(new java.awt.Color(255, 255, 255));
        btnCapturar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCapturar.setForeground(new java.awt.Color(0, 0, 0));
        btnCapturar.setText("Capturar");
        btnCapturar.addActionListener(this::btnCapturarActionPerformed);
        jPanel3.add(btnCapturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnPresentar.setBackground(new java.awt.Color(255, 255, 255));
        btnPresentar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnPresentar.setForeground(new java.awt.Color(0, 0, 0));
        btnPresentar.setText("Presentar");
        btnPresentar.addActionListener(this::btnPresentarActionPerformed);
        jPanel3.add(btnPresentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 400, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuatriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuatriActionPerformed
     ProcesarDatos capt = new ProcesarDatos();
    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
       validarCampos();
       
       
       
       String nombres = txtNombres.getText();
       String apellidos = txtApellidos.getText();
       String matricula = txtMatricula.getText();
       String cuatri = txtCuatri.getText();
       
       capt.capturarDatos(nombres, apellidos, matricula, cuatri);
    }//GEN-LAST:event_btnCapturarActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnResetearActionPerformed
   
    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed
        
        
        
        String resultado = capt.presentarDatos();
        
        JOptionPane.showMessageDialog(this,resultado);
    }//GEN-LAST:event_btnPresentarActionPerformed

    
     private void validarCampos()
    {
        if(txtNombres.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar los Nombre");
            txtNombres.requestFocus();
        } else if(txtApellidos.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar los Apellidos");
            txtApellidos.requestFocus();
        } else if (txtMatricula.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar la matricula");
            txtMatricula.requestFocus(); 
        }else if (txtCuatri.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el cuatrimestre");
            txtCuatri.requestFocus(); 
        }
    }
     
     private void limpiarCampos(){
         txtNombres.setText("");
         txtApellidos.setText("");
         txtMatricula.setText("");
         txtCuatri.setText("");
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProcesarDatosGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnPresentar;
    private javax.swing.JButton btnResetear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCuatri;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
