/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora_gui;

/**
 *
 * @author Joshua Abreu
 */
public class Conversor_Temperatura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Conversor_Temperatura.class.getName());

    /**
     * Creates new form Conversor_Temperatura
     */
    public Conversor_Temperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblConversor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtFahrenheit = new javax.swing.JTextField();
        txtCelsius = new javax.swing.JTextField();
        jlbCelsius = new javax.swing.JLabel();
        jlbFahrenheit = new javax.swing.JLabel();
        jlbResultado_temp = new javax.swing.JLabel();
        txtResultado_temp = new javax.swing.JTextField();
        btnCtoF = new javax.swing.JButton();
        btnFtoC = new javax.swing.JButton();
        jbtVolverCalculadora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        lblConversor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblConversor.setForeground(new java.awt.Color(255, 255, 255));
        lblConversor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConversor.setText("Conversor de Temperatura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConversor)
                .addGap(230, 230, 230))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblConversor)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        txtFahrenheit.addActionListener(this::txtFahrenheitActionPerformed);
        txtFahrenheit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFahrenheitKeyTyped(evt);
            }
        });

        txtCelsius.addActionListener(this::txtCelsiusActionPerformed);
        txtCelsius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelsiusKeyTyped(evt);
            }
        });

        jlbCelsius.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlbCelsius.setForeground(new java.awt.Color(255, 255, 255));
        jlbCelsius.setText("Celsius a Fahrenheit");

        jlbFahrenheit.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlbFahrenheit.setForeground(new java.awt.Color(255, 255, 255));
        jlbFahrenheit.setText("Fahrenheit a Celsius");

        jlbResultado_temp.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlbResultado_temp.setForeground(new java.awt.Color(255, 255, 255));
        jlbResultado_temp.setText("Resultado");

        txtResultado_temp.setEditable(false);
        txtResultado_temp.addActionListener(this::txtResultado_tempActionPerformed);
        txtResultado_temp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado_tempKeyTyped(evt);
            }
        });

        btnCtoF.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnCtoF.setText("C → F");
        btnCtoF.addActionListener(this::btnCtoFActionPerformed);

        btnFtoC.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnFtoC.setText("F → C");
        btnFtoC.addActionListener(this::btnFtoCActionPerformed);

        jbtVolverCalculadora.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jbtVolverCalculadora.setText("Volver a Calculadora");
        jbtVolverCalculadora.addActionListener(this::jbtVolverCalculadoraActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jlbCelsius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbFahrenheit)
                .addGap(126, 126, 126))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(txtFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnCtoF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFtoC, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jlbResultado_temp))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(txtResultado_temp, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtVolverCalculadora)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCelsius)
                    .addComponent(jlbFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtoF)
                    .addComponent(btnFtoC))
                .addGap(72, 72, 72)
                .addComponent(jlbResultado_temp)
                .addGap(18, 18, 18)
                .addComponent(txtResultado_temp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtVolverCalculadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFahrenheitActionPerformed

    private void txtFahrenheitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFahrenheitKeyTyped
      
    }//GEN-LAST:event_txtFahrenheitKeyTyped

    private void txtCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelsiusActionPerformed

    private void txtCelsiusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelsiusKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelsiusKeyTyped

    private void txtResultado_tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultado_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultado_tempActionPerformed

    private void txtResultado_tempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado_tempKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultado_tempKeyTyped
    /**
    * Convierte una temperatura de Celsius a Fahrenheit.
    * Valida que el campo no esté vacío y que el valor sea numérico.
    */
    private void btnCtoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoFActionPerformed
        try {
        if (txtCelsius.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor en Celsius");
            return;
        }

        double celsius = Double.parseDouble(txtCelsius.getText());

        double fahrenheit = (celsius * 9/5) + 32;

        // Mostrar resultado
        txtResultado_temp.setText(fahrenheit + " °F");

        // Limpiar el otro campo
        txtFahrenheit.setText("");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido en Celsius");
    }
    }//GEN-LAST:event_btnCtoFActionPerformed
    /**
    * Convierte una temperatura de Fahrenheit a Celsius.
    * Valida que el campo no esté vacío y que el valor sea numérico.
    */
    private void btnFtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFtoCActionPerformed
        try {
        if (txtFahrenheit.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor en Fahrenheit");
            return;
        }

        double fahrenheit = Double.parseDouble(txtFahrenheit.getText());

        double celsius = (fahrenheit - 32) * 5/9;

        // Mostrar resultado
        txtResultado_temp.setText(celsius + " °C");

        // Limpiar el otro campo
        txtCelsius.setText("");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido en Fahrenheit");
    }
    }//GEN-LAST:event_btnFtoCActionPerformed
    //Abre la ventana de la calculadora y cierra la del conversor.
    private void jbtVolverCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVolverCalculadoraActionPerformed
        CalculadoraUI cal = new CalculadoraUI();
        cal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtVolverCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Conversor_Temperatura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCtoF;
    private javax.swing.JButton btnFtoC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtVolverCalculadora;
    private javax.swing.JLabel jlbCelsius;
    private javax.swing.JLabel jlbFahrenheit;
    private javax.swing.JLabel jlbResultado_temp;
    private javax.swing.JLabel lblConversor;
    private javax.swing.JTextField txtCelsius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtResultado_temp;
    // End of variables declaration//GEN-END:variables
}
