package RegistroAcademico;

import javax.swing.JOptionPane;

/**
 * Interfaz gráfica para registrar datos del estudiante
 * y calcular su resultado académico.
 * @author Surky
 */
public class RegistroAcademicoGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAcademicoGUI
     */
    public RegistroAcademicoGUI() {
        initComponents();
        txtNotaTotal.setEditable(false);
        txtMensaje.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAsignaciones = new javax.swing.JTextField();
        txtParciales = new javax.swing.JTextField();
        txtExamenFinal = new javax.swing.JTextField();
        txtPracticas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtNotaTotal = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 480, -1));

        jPanel7.setBackground(new java.awt.Color(191, 207, 222));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(55, 71, 89));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular y Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 320, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(55, 71, 89));
        jLabel15.setText("Calculadora de calificaciones");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 390, 24));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Practicas (Máx 40) :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Asignaciones (Máx 20): ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Parciales (Máx 20):");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Examen final (Máx 20):");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txtAsignaciones.setBackground(new java.awt.Color(204, 204, 204));
        txtAsignaciones.addActionListener(this::txtAsignacionesActionPerformed);
        jPanel5.add(txtAsignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 20));

        txtParciales.setBackground(new java.awt.Color(204, 204, 204));
        txtParciales.addActionListener(this::txtParcialesActionPerformed);
        jPanel5.add(txtParciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 30, 80, 20));

        txtExamenFinal.setBackground(new java.awt.Color(204, 204, 204));
        txtExamenFinal.addActionListener(this::txtExamenFinalActionPerformed);
        jPanel5.add(txtExamenFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 60, 20));

        txtPracticas.setBackground(new java.awt.Color(204, 204, 204));
        txtPracticas.addActionListener(this::txtPracticasActionPerformed);
        jPanel5.add(txtPracticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 20));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 480, 120));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Por favor, ingrese los datos del estudiante para calcular el resultado final ");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nota total :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        txtNotaTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtNotaTotal.addActionListener(this::txtNotaTotalActionPerformed);
        jPanel3.add(txtNotaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 83, -1));

        txtMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtMensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(0, 0, 0));
        txtMensaje.addActionListener(this::txtMensajeActionPerformed);
        jPanel3.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 360, 30));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 480, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtMatricula.setBackground(new java.awt.Color(204, 204, 204));
        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);
        jPanel2.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 340, 20));

        txtCarrera.setBackground(new java.awt.Color(204, 204, 204));
        txtCarrera.addActionListener(this::txtCarreraActionPerformed);
        jPanel2.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 340, 20));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 300, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre completo : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Carrera :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Matricula :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 480, 140));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Calificaciones");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Datos del Estudiante");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!validarCampos()) {
            return;
        }

        try {
            Estudiante estudiante = crearEstudiante();
            mostrarResultado(estudiante);
            //limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarreraActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsignacionesActionPerformed

    private void txtExamenFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenFinalActionPerformed

    private void txtPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticasActionPerformed

    private void txtNotaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaTotalActionPerformed

    private void txtMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajeActionPerformed

    private void txtParcialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParcialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcialesActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * Verifica que todos los campos del formulario estén completos.
     * @return true si todos los campos tienen datos
     */
    private boolean validarCampos() {

        if (txtNombre.getText().trim().isEmpty()
                || txtMatricula.getText().trim().isEmpty()
                || txtCarrera.getText().trim().isEmpty()
                || txtPracticas.getText().trim().isEmpty()
                || txtParciales.getText().trim().isEmpty()
                || txtAsignaciones.getText().trim().isEmpty()
                || txtExamenFinal.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return false;
        }

        return true;
    }

    private void validarRangos(double practicas, double parciales,
            double asignaciones, double examenFinal) {

        if (practicas < 0 || practicas > 40) {
            throw new NumberFormatException("Prácticas fuera de rango");
        }

        if (parciales < 0 || parciales > 20) {
            throw new NumberFormatException("Parciales fuera de rango");
        }

        if (asignaciones < 0 || asignaciones > 20) {
            throw new NumberFormatException("Asignaciones fuera de rango");
        }

        if (examenFinal < 0 || examenFinal > 20) {
            throw new NumberFormatException("Examen fuera de rango");
        }
    }
    
    /**
     * Crea un objeto Estudiante con los datos ingresados en la interfaz.
     * @return objeto Estudiante con sus datos y calificaciones
     */
    private Estudiante crearEstudiante() {

        double practicas = Double.parseDouble(txtPracticas.getText());
        double parciales = Double.parseDouble(txtParciales.getText());
        double asignaciones = Double.parseDouble(txtAsignaciones.getText());
        double examenFinal = Double.parseDouble(txtExamenFinal.getText());

        validarRangos(practicas, parciales, asignaciones, examenFinal);

        Estudiante estudiante = new Estudiante(
                txtNombre.getText(),
                txtMatricula.getText(),
                txtCarrera.getText(),
                practicas,
                parciales,
                asignaciones,
                examenFinal
        );

        return estudiante;
    }
    
    /**
     * Muestra en la interfaz la nota total y el resultado final.
     */
    private void mostrarResultado(Estudiante estudiante) {

        double total = estudiante.calcularNota();

        txtNotaTotal.setText(String.valueOf(total));
        txtMensaje.setText("Resultado: " + estudiante.obtenerResultado());
    }

    /**
     * Limpia los campos del formulario después del cálculo.
     */
    private void limpiarCampos() {
        txtNombre.setText("");
        txtMatricula.setText("");
        txtCarrera.setText("");
        txtPracticas.setText("");
        txtParciales.setText("");
        txtAsignaciones.setText("");
        txtExamenFinal.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtAsignaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtExamenFinal;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNotaTotal;
    private javax.swing.JTextField txtParciales;
    private javax.swing.JTextField txtPracticas;
    // End of variables declaration//GEN-END:variables
}
