/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registro_academico;

/**
 *
 * @author Joshua Abreu
 */
public class Registro_Academico_GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_Academico_GUI.class.getName());

    /**
     * Creates new form Registro_Academico_GUI
     */
    public Registro_Academico_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbRegistro = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlbCarrera = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jlbNombre1 = new javax.swing.JLabel();
        jlbMatricula = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jbtSiguiente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlbRegistro2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jlbParciales = new javax.swing.JLabel();
        txtParciales = new javax.swing.JTextField();
        jlbAsignacion = new javax.swing.JLabel();
        txtPracticas = new javax.swing.JTextField();
        jlbPracticas = new javax.swing.JLabel();
        txtExamen = new javax.swing.JTextField();
        jlbExamen = new javax.swing.JLabel();
        jbtCalcular = new javax.swing.JButton();
        txtAsignaciones = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jlbRegistro.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jlbRegistro.setForeground(new java.awt.Color(0, 0, 0));
        jlbRegistro.setText("Registro Académico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbRegistro)
                .addGap(235, 235, 235))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlbRegistro)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbCarrera.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbCarrera.setForeground(new java.awt.Color(0, 0, 0));
        jlbCarrera.setText("Carrera:");

        txtMatricula.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);

        jlbNombre1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbNombre1.setForeground(new java.awt.Color(0, 0, 0));
        jlbNombre1.setText("Nombre:");

        jlbMatricula.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbMatricula.setForeground(new java.awt.Color(0, 0, 0));
        jlbMatricula.setText("Matrícula:");

        txtCarrera.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtCarrera.addActionListener(this::txtCarreraActionPerformed);

        txtNombre.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jbtSiguiente.setBackground(new java.awt.Color(51, 204, 0));
        jbtSiguiente.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jbtSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        jbtSiguiente.setText("Siguiente");
        jbtSiguiente.addActionListener(this::jbtSiguienteActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbNombre1)
                        .addGap(310, 310, 310))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jlbMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbCarrera)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNombre1)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMatricula)
                    .addComponent(jlbCarrera))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jbtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        jTabbedPane1.addTab("Datos Estudiantes", jTabbedPane2);

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jlbRegistro2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jlbRegistro2.setForeground(new java.awt.Color(0, 0, 0));
        jlbRegistro2.setText("Registro Académico");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jlbRegistro2)
                .addGap(235, 235, 235))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlbRegistro2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jlbParciales.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbParciales.setForeground(new java.awt.Color(0, 0, 0));
        jlbParciales.setText("Parciales:");

        txtParciales.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtParciales.addActionListener(this::txtParcialesActionPerformed);

        jlbAsignacion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbAsignacion.setForeground(new java.awt.Color(0, 0, 0));
        jlbAsignacion.setText("Asignaciones:");

        txtPracticas.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtPracticas.addActionListener(this::txtPracticasActionPerformed);

        jlbPracticas.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbPracticas.setForeground(new java.awt.Color(0, 0, 0));
        jlbPracticas.setText("Prácticas:");

        txtExamen.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtExamen.addActionListener(this::txtExamenActionPerformed);

        jlbExamen.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jlbExamen.setForeground(new java.awt.Color(0, 0, 0));
        jlbExamen.setText("Examen Final:");

        jbtCalcular.setBackground(new java.awt.Color(102, 204, 0));
        jbtCalcular.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jbtCalcular.setForeground(new java.awt.Color(0, 0, 0));
        jbtCalcular.setText("Calcular Resultado");
        jbtCalcular.addActionListener(this::jbtCalcularActionPerformed);

        txtAsignaciones.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtAsignaciones.addActionListener(this::txtAsignacionesActionPerformed);

        txtResultado.setEditable(false);
        txtResultado.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jlbAsignacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jlbParciales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jlbExamen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jbtCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jlbPracticas)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbParciales)
                    .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAsignacion)
                    .addComponent(jlbExamen)
                    .addComponent(txtExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jbtCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jlbPracticas)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calificaciones", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarreraActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    /**
    * Evento del botón "Siguiente".
    * Valida los datos personales del estudiante y, si son correctos,
    * cambia a la pestaña de calificaciones.
    */
    private void jbtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSiguienteActionPerformed
        String nombre = txtNombre.getText();
        String matricula = txtMatricula.getText();
        String carrera = txtCarrera.getText();
         // Validar campos vacíos
        if (nombre.isEmpty() || matricula.isEmpty() || carrera.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }
        //Validar que el nombre solo contenga letras
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nombre inválido");
            return;
        }
         // Validar que la carrera solo contenga letras
        if (!carrera.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Carrera inválida");
            return;
        }
         // Validar que la matrícula solo tenga números y guiones
        if (!matricula.matches("[0-9-]+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Matrícula inválida");
            return;
        }
        // Si todo está bien cambiar de pestaña
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jbtSiguienteActionPerformed

    private void txtParcialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParcialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcialesActionPerformed

    private void txtPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPracticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPracticasActionPerformed

    private void txtExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenActionPerformed
    /**
    * Evento del botón "Calcular".
    * Calcula la nota final del estudiante y determina si está aprobado o reprobado.
    * También valida los rangos de cada calificación.
    */
    private void jbtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularActionPerformed
        try {
        double practicas = Double.parseDouble(txtPracticas.getText());
        double parciales = Double.parseDouble(txtParciales.getText());
        double asignaciones = Double.parseDouble(txtAsignaciones.getText());
        double examen = Double.parseDouble(txtExamen.getText());

        // Validar rangos
        if (practicas < 0 || practicas > 40 ||
            parciales < 0 || parciales > 20 ||
            asignaciones < 0 || asignaciones > 20 ||
            examen < 0 || examen > 20) {

            javax.swing.JOptionPane.showMessageDialog(this, "Valores fuera de rango");
            return;
        }

        // Calcular total
        double total = practicas + parciales + asignaciones + examen;

        // Determinar estado
        if (total >= 60) {
        txtResultado.setText("APROBADO - " + total + " puntos");
        txtResultado.setBackground(java.awt.Color.GREEN);
        txtResultado.setForeground(java.awt.Color.BLACK);
    } else {
        txtResultado.setText("REPROBADO - " + total + " puntos");
        txtResultado.setBackground(java.awt.Color.RED);
        txtResultado.setForeground(java.awt.Color.WHITE);
    }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese solo números en las notas");
    }
    }//GEN-LAST:event_jbtCalcularActionPerformed

    private void txtAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsignacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro_Academico_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbtCalcular;
    private javax.swing.JButton jbtSiguiente;
    private javax.swing.JLabel jlbAsignacion;
    private javax.swing.JLabel jlbCarrera;
    private javax.swing.JLabel jlbExamen;
    private javax.swing.JLabel jlbMatricula;
    private javax.swing.JLabel jlbNombre1;
    private javax.swing.JLabel jlbParciales;
    private javax.swing.JLabel jlbPracticas;
    private javax.swing.JLabel jlbRegistro;
    private javax.swing.JLabel jlbRegistro2;
    private javax.swing.JTextField txtAsignaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtExamen;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtParciales;
    private javax.swing.JTextField txtPracticas;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
