package com.mycompany.calculadora_gui;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Joshua Abreu
 */
public class CalculadoraUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraUI.class.getName());

    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jlbValor1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jlbValor2 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        jlbRespuesta = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        plOperaciones = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        jbtIrConversor = new javax.swing.JButton();
        jbtRaiz = new javax.swing.JButton();
        jbtPotencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(0, 153, 204));

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Basica");

        javax.swing.GroupLayout plTituloLayout = new javax.swing.GroupLayout(plTitulo);
        plTitulo.setLayout(plTituloLayout);
        plTituloLayout.setHorizontalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTituloLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(lblTitulo)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        plTituloLayout.setVerticalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plTituloLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(22, 22, 22))
        );

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 80));

        plValores.setBackground(new java.awt.Color(153, 153, 153));

        jlbValor1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlbValor1.setForeground(new java.awt.Color(255, 255, 255));
        jlbValor1.setText("Valor 1:");

        txtValor1.addActionListener(this::txtValor1ActionPerformed);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });

        jlbValor2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlbValor2.setForeground(new java.awt.Color(255, 255, 255));
        jlbValor2.setText("Valor 2:");

        txtRespuesta.setEditable(false);
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRespuesta.addActionListener(this::txtRespuestaActionPerformed);

        jlbRespuesta.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jlbRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        jlbRespuesta.setText("Respuesta");

        txtValor2.addActionListener(this::txtValor2ActionPerformed);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout plValoresLayout = new javax.swing.GroupLayout(plValores);
        plValores.setLayout(plValoresLayout);
        plValoresLayout.setHorizontalGroup(
            plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plValoresLayout.createSequentialGroup()
                .addGroup(plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plValoresLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jlbRespuesta))
                    .addGroup(plValoresLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbValor2)
                            .addComponent(jlbValor1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(plValoresLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        plValoresLayout.setVerticalGroup(
            plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plValoresLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbValor1))
                .addGap(56, 56, 56)
                .addGroup(plValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbValor2))
                .addGap(59, 59, 59)
                .addComponent(jlbRespuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, 350));

        plOperaciones.setBackground(new java.awt.Color(255, 255, 255));

        btnSumar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSumar.setText("Sumar");
        btnSumar.addActionListener(this::btnSumarActionPerformed);

        btnRestar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnRestar.setText("Restar");
        btnRestar.addActionListener(this::btnRestarActionPerformed);

        btnMultiplicar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(this::btnMultiplicarActionPerformed);

        btnDividir.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnDividir.setText("Dividir");
        btnDividir.addActionListener(this::btnDividirActionPerformed);

        btnResetear.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnResetear.setText("Resetear");
        btnResetear.addActionListener(this::btnResetearActionPerformed);

        jbtIrConversor.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jbtIrConversor.setText("Ir a Convertido de Temperatura");
        jbtIrConversor.addActionListener(this::jbtIrConversorActionPerformed);

        jbtRaiz.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jbtRaiz.setText("Raiz cuadrada");
        jbtRaiz.addActionListener(this::jbtRaizActionPerformed);

        jbtPotencia.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jbtPotencia.setText("Potenciación");
        jbtPotencia.addActionListener(this::jbtPotenciaActionPerformed);

        javax.swing.GroupLayout plOperacionesLayout = new javax.swing.GroupLayout(plOperaciones);
        plOperaciones.setLayout(plOperacionesLayout);
        plOperacionesLayout.setHorizontalGroup(
            plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plOperacionesLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(plOperacionesLayout.createSequentialGroup()
                .addGroup(plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plOperacionesLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnResetear, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plOperacionesLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jbtIrConversor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plOperacionesLayout.setVerticalGroup(
            plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plOperacionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumar)
                    .addComponent(jbtRaiz))
                .addGap(34, 34, 34)
                .addGroup(plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestar)
                    .addComponent(jbtPotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(plOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiplicar)
                    .addComponent(btnDividir))
                .addGap(63, 63, 63)
                .addComponent(btnResetear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jbtIrConversor)
                .addContainerGap())
        );

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 430, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor2ActionPerformed
    /**
    * Evento que se ejecuta al presionar el botón Restar.
    * Valida los campos y luego realiza la operación.
    */
    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_btnRestarActionPerformed
    
    //Evento que valida que solo se ingresen números en txtValor1.
    
    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros> '.')){
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped
    //Evento que valida que solo se ingresen números en txtValor2.
    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros> '.')){
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped
    //Limpia todos los campos del formulario.
    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnResetearActionPerformed
    //Evento para multiplicar valores.
    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_btnMultiplicarActionPerformed
    //Evento para dividir valores con validación de división por cero.
    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        validarCampos();
        divisionValores();
    }//GEN-LAST:event_btnDividirActionPerformed
    //Evento para sumar valores.
    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_btnSumarActionPerformed
    //Abre la ventana del conversor de temperatura y cierra la actual.
    private void jbtIrConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIrConversorActionPerformed
        Conversor_Temperatura conv = new Conversor_Temperatura();
        conv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtIrConversorActionPerformed
    /**
    * Calcula la raíz cuadrada de un número.
    * Valida que el campo no esté vacío y que el número no sea negativo.
    */
    private void jbtRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRaizActionPerformed
        try{
            if(txtValor1.getText().isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número en el Valor 1");
                return;
            }
            double num = Double.parseDouble(txtValor1.getText());
            if(num < 0){
                javax.swing.JOptionPane.showMessageDialog(this, "No se puede sacar raíz de un número negativo");
                return;
            }
            double resultado = Math.sqrt(num);
            txtRespuesta.setText(resultado + "");
            
            //Limpiar el segundo valor
            txtValor2.setText("");
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido en Valor 1");
        }
    }//GEN-LAST:event_jbtRaizActionPerformed
    /**
    * Calcula la potencia de un número.
    * Usa txtValor1 como base y txtValor2 como exponente.
    */
    private void jbtPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPotenciaActionPerformed
        try {
        // Validar campos vacíos
        if (txtValor1.getText().isEmpty() || txtValor2.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese valores en ambos campos");
            return;
        }

        double base = Double.parseDouble(txtValor1.getText());
        double exponente = Double.parseDouble(txtValor2.getText());

        double resultado = Math.pow(base, exponente);

        txtRespuesta.setText(resultado + "");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese números válidos");
    }
    }//GEN-LAST:event_jbtPotenciaActionPerformed
    //Valida que los campos no estén vacíos antes de realizar operaciones.
    private void validarCampos(){
        if(txtValor1.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, porque el campo esta vacio.");
            txtValor1.requestFocus();
        }else if(txtValor2.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 2, porque el campo esta vacio.");
            txtValor2.requestFocus();
        }
    }
    //Realiza la suma de los valores ingresados.
    private void sumarValores(){
        Calculadora_GUI cal = new Calculadora_GUI();
        Double respuesta =  cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");   
    }
    //Limpia todos los campos del formulario.
    private void limpiarCampos(){
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
    }
    //Realiza la resta de los valores ingresados.
    private void restarValores(){
        Calculadora_GUI cal = new Calculadora_GUI();
        Double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");
    }
    //Realiza la multiplicación de los valores ingresados.
    private void multiplicarValores(){
        Calculadora_GUI cal = new Calculadora_GUI();
        Double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta + "");
    }
    /**
    * Realiza la división de los valores ingresados.
    * Incluye validación para evitar división entre cero.
    */
    private void divisionValores(){
        double num1 = Double.parseDouble(txtValor1.getText());
        double num2 = Double.parseDouble(txtValor2.getText());

        if (num2 == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se puede dividir entre cero");
            return;
        }
        Calculadora_GUI cal = new Calculadora_GUI();
        Double respuesta = cal.dividir(num1, num2);
        txtRespuesta.setText(respuesta + "");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnResetear;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton jbtIrConversor;
    private javax.swing.JButton jbtPotencia;
    private javax.swing.JButton jbtRaiz;
    private javax.swing.JLabel jlbRespuesta;
    private javax.swing.JLabel jlbValor1;
    private javax.swing.JLabel jlbValor2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
