/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica_4_java_swing;

import javax.swing.JOptionPane;

/**
 *
 * @author gilbe
 */
public class CalculadoraExtendidaGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraExtendidaGUI.class.getName());

    /**
     * Creates new form CalculadoraExtendidaGUI
     */
    public CalculadoraExtendidaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        plTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnValores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        pnBotones = new javax.swing.JPanel();
        bntSumar = new javax.swing.JButton();
        bntRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        bntDividir = new javax.swing.JButton();
        pnResultado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        bntResetear = new javax.swing.JButton();
        btnConvertidor = new javax.swing.JButton();
        btnRaizYExponente = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(199, 101, 101));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calculadora Extendida");
        plTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 310, 20));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 70));

        pnValores.setBackground(new java.awt.Color(0, 0, 0));
        pnValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Valor 1: ");
        pnValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresa un valor ");
        pnValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        txtValor1.setBackground(new java.awt.Color(255, 255, 255));
        txtValor1.setForeground(new java.awt.Color(0, 0, 0));
        txtValor1.addActionListener(this::txtValor1ActionPerformed);
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        pnValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor 2:");
        pnValores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 20));

        txtValor2.setBackground(new java.awt.Color(255, 255, 255));
        txtValor2.setForeground(new java.awt.Color(0, 0, 0));
        txtValor2.addActionListener(this::txtValor2ActionPerformed);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        pnValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 80, 30));

        getContentPane().add(pnValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 560, 130));

        pnBotones.setBackground(new java.awt.Color(255, 102, 102));
        pnBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntSumar.setBackground(new java.awt.Color(255, 255, 255));
        bntSumar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bntSumar.setForeground(new java.awt.Color(0, 0, 0));
        bntSumar.setText("Sumar ");
        bntSumar.addActionListener(this::bntSumarActionPerformed);
        pnBotones.add(bntSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        bntRestar.setBackground(new java.awt.Color(255, 255, 255));
        bntRestar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bntRestar.setForeground(new java.awt.Color(0, 0, 0));
        bntRestar.setText("Restar");
        bntRestar.addActionListener(this::bntRestarActionPerformed);
        pnBotones.add(bntRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        btnMultiplicar.setBackground(new java.awt.Color(255, 255, 255));
        btnMultiplicar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(0, 0, 0));
        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(this::btnMultiplicarActionPerformed);
        pnBotones.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        bntDividir.setBackground(new java.awt.Color(255, 255, 255));
        bntDividir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bntDividir.setForeground(new java.awt.Color(0, 0, 0));
        bntDividir.setText("Dividir");
        bntDividir.addActionListener(this::bntDividirActionPerformed);
        pnBotones.add(bntDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        getContentPane().add(pnBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 560, 130));

        pnResultado.setBackground(new java.awt.Color(0, 0, 0));
        pnResultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Respuesta");
        pnResultado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.addActionListener(this::txtResultadoActionPerformed);
        pnResultado.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 40));

        bntResetear.setBackground(new java.awt.Color(255, 255, 255));
        bntResetear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bntResetear.setForeground(new java.awt.Color(0, 0, 0));
        bntResetear.setText("Resetear");
        bntResetear.addActionListener(this::bntResetearActionPerformed);
        pnResultado.add(bntResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnConvertidor.setBackground(new java.awt.Color(255, 255, 255));
        btnConvertidor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConvertidor.setForeground(new java.awt.Color(0, 0, 0));
        btnConvertidor.setText("Convertidor");
        btnConvertidor.addActionListener(this::btnConvertidorActionPerformed);
        pnResultado.add(btnConvertidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 20));

        btnRaizYExponente.setBackground(new java.awt.Color(255, 255, 255));
        btnRaizYExponente.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnRaizYExponente.setForeground(new java.awt.Color(0, 0, 0));
        btnRaizYExponente.setText("Raiz y exponente");
        btnRaizYExponente.addActionListener(this::btnRaizYExponenteActionPerformed);
        pnResultado.add(btnRaizYExponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        getContentPane().add(pnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 560, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor2ActionPerformed

    private void bntRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestarActionPerformed
        validarCampos();
        
        Calculadora calRes = new Calculadora();
        
        double valor1 = Double.parseDouble(txtValor1.getText());
        double valor2 = Double.parseDouble(txtValor2.getText());
        
        double resultado = calRes.restar(valor1, valor2);
        
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bntRestarActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void bntResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntResetearActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_bntResetearActionPerformed

    private void limpiarCampos(){
        txtValor1.setText("");
        txtValor2.setText("");
        txtResultado.setText("");
    }
    
    /**
     * Aqui lo que hago es crear un objeto de la ventana creada para poder
     * mostrarla
     * @param evt 
     */
    private void btnConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertidorActionPerformed
        ConvertidorDeGradosGUI v = new ConvertidorDeGradosGUI();
        v.setVisible(true);
    }//GEN-LAST:event_btnConvertidorActionPerformed

    private void bntSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSumarActionPerformed
        validarCampos();
        
        /**
         * Aqui creo un objeto para poder utilizar el metodo de la clase 
         * calculadora
         */
        Calculadora cal = new Calculadora();
        
        double valor1 = Double.parseDouble(txtValor1.getText());
        double valor2 = Double.parseDouble(txtValor2.getText());
        
        double resultado = cal.sumar(valor1, valor2);
        
        /**
         * Aqui paso a enviar el resultado al txt correspondiente
         * (convirtiendolo en string)
         */
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_bntSumarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        validarCampos();
        
        /**
         * Aqui creo un objeto para poder utilizar el metodo de la clase 
         * calculadora
         */
        Calculadora calMul = new Calculadora();
        
        double valor1 = Double.parseDouble(txtValor1.getText());
        double valor2 = Double.parseDouble(txtValor2.getText());
        
        double resultado = calMul.multiplicar(valor1, valor2);
        
        /**
         * Aqui paso a enviar el resultado al txt correspondiente
         * (convirtiendolo en string)
         */
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void bntDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDividirActionPerformed
        validarCampos();
        
        /**
         * Aqui creo un objeto para poder utilizar el metodo de la clase 
         * calculadora
         */
        Calculadora calDiv = new Calculadora();
        
        double valor1 = Double.parseDouble(txtValor1.getText());
        double valor2 = Double.parseDouble(txtValor2.getText());
        
        /**
         * Verificamos de que no se este dividiendo por 0
         */
        if ( valor2 !=0 ){
            double resultado = calDiv.dividir(valor1, valor2);
            txtResultado.setText(String.valueOf(resultado));
        }
        else{
            String resultado = "No se puede dividir en 0";
            txtResultado.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_bntDividirActionPerformed

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "por favor agregar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "por favor agregar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    private void btnRaizYExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizYExponenteActionPerformed
        RaizYExponenteGUI v = new RaizYExponenteGUI();
        v.setVisible(true);
    }//GEN-LAST:event_btnRaizYExponenteActionPerformed

    /**
     * Este metodo es para poder validar que los txt no esten 
     * vacios a la hora de ejecutar cualquier operacion
     */
    private void validarCampos()
    {
        if(txtValor1.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el valor 1");
            txtValor1.requestFocus();
        } else if(txtValor2.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el valor 2");
            txtValor2.requestFocus();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraExtendidaGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDividir;
    private javax.swing.JButton bntResetear;
    private javax.swing.JButton bntRestar;
    private javax.swing.JButton bntSumar;
    private javax.swing.JButton btnConvertidor;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRaizYExponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnResultado;
    private javax.swing.JPanel pnValores;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
