/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemanota;

import javax.swing.JOptionPane;

/**
 *
 * @author gilbe
 */
public class SistemaNotaGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SistemaNotaGUI.class.getName());

    /**
     * Creates new form SistemaNotaGUI
     */
    public SistemaNotaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        plOperaciones = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPracticas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtParciales = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAsignaciones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtExamen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(80, 140, 171));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Notas");

        javax.swing.GroupLayout plTituloLayout = new javax.swing.GroupLayout(plTitulo);
        plTitulo.setLayout(plTituloLayout);
        plTituloLayout.setHorizontalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTituloLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblTitulo)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        plTituloLayout.setVerticalGroup(
            plTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        plValores.setBackground(new java.awt.Color(0, 51, 51));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre completo:");
        plValores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        plValores.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Matricula:");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.addActionListener(this::txtMatriculaActionPerformed);
        plValores.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carrera:");
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtCarrera.setBackground(new java.awt.Color(255, 255, 255));
        txtCarrera.setForeground(new java.awt.Color(0, 0, 0));
        txtCarrera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCarrera.addActionListener(this::txtCarreraActionPerformed);
        plValores.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 30));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 100));

        plOperaciones.setBackground(new java.awt.Color(0, 51, 51));
        plOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcular.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcular.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);
        plOperaciones.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, 30));

        btnResetear.setBackground(new java.awt.Color(255, 255, 255));
        btnResetear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnResetear.setForeground(new java.awt.Color(0, 0, 0));
        btnResetear.setText("Resetear");
        btnResetear.addActionListener(this::btnResetearActionPerformed);
        plOperaciones.add(btnResetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plOperaciones.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 190, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Respuesta");
        plOperaciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 20));

        getContentPane().add(plOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 450, 120));

        jPanel1.setBackground(new java.awt.Color(80, 140, 171));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingresa tus calificaciones");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Practicas: ");

        txtPracticas.setBackground(new java.awt.Color(255, 255, 255));
        txtPracticas.setForeground(new java.awt.Color(0, 0, 0));
        txtPracticas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPracticas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPracticasKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Parciales:");

        txtParciales.setBackground(new java.awt.Color(255, 255, 255));
        txtParciales.setForeground(new java.awt.Color(0, 0, 0));
        txtParciales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtParciales.addActionListener(this::txtParcialesActionPerformed);
        txtParciales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParcialesKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Asignaciones:");

        txtAsignaciones.setBackground(new java.awt.Color(255, 255, 255));
        txtAsignaciones.setForeground(new java.awt.Color(0, 0, 0));
        txtAsignaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAsignaciones.addActionListener(this::txtAsignacionesActionPerformed);
        txtAsignaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAsignacionesKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Examen final:");

        txtExamen.setBackground(new java.awt.Color(255, 255, 255));
        txtExamen.setForeground(new java.awt.Color(0, 0, 0));
        txtExamen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExamen.addActionListener(this::txtExamenActionPerformed);
        txtExamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExamenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtParciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAsignaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarreraActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        limpiezaCampos();
    }//GEN-LAST:event_btnResetearActionPerformed

    /**
     * Esto es del boton resetear, lo que hace es que escribe
     * (por asi decirlo) las casillas y se limpian despues de precionar
     */
    private void limpiezaCampos(){
        txtNombre.setText("");
        txtCarrera.setText("");
        txtMatricula.setText("");
        txtPracticas.setText("");
        txtParciales.setText("");
        txtAsignaciones.setText("");
        txtExamen.setText("");
        txtResultado.setText("");
    }
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        validarCampos();
        validarCamposPerso();
        /**
         * Aqui paso a cambiar de texto a double para poder hacer 
         * los calculos 
         */
        double prac = Double.parseDouble(txtPracticas.getText());
        double par = Double.parseDouble(txtParciales.getText());
        double asig = Double.parseDouble(txtAsignaciones.getText());
        double exam = Double.parseDouble(txtExamen.getText());

        /**
         * Aqui pasamos a usar el metodo de evaluar el estudiante
         */
        String resultado = SistemaNota.evaluarEstudiante(prac, par, asig, exam);

        // Esto se usa para mostrar el resultado en la caja de texto definida
        txtResultado.setText(resultado);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void validarCampos(){
        
        /**
         * Estos if son para mostrar un mensaje a la hora que se deje
         * un campo vacio y le demos al boton de calcular
         */
        if(txtPracticas.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el valor en practicas");
            txtPracticas.requestFocus();
        } else if(txtParciales.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el valor en parciales");
            txtParciales.requestFocus();
        } else if(txtAsignaciones.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el valor en asignaciones");
            txtAsignaciones.requestFocus();
        } else if(txtExamen.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar el valor en examen final");
            txtExamen.requestFocus();
        }
    }
    /**
     * Este metodo tiene la misma funcion que el de validarCampos
     */
    private void validarCamposPerso(){
        if(txtNombre.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar su nombre");
            txtNombre.requestFocus();
        } else if(txtCarrera.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar su carrera");
            txtCarrera.requestFocus();
        } else if(txtMatricula.getText().trim().length()<= 0){
            JOptionPane.showMessageDialog(null,"Por favor ingresar su matricula");
            txtMatricula.requestFocus();
        }
    }
    private void txtParcialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParcialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcialesActionPerformed

    private void txtAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsignacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsignacionesActionPerformed

    private void txtExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamenActionPerformed

    private void txtPracticasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPracticasKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "por favor agregar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_txtPracticasKeyTyped

    private void txtAsignacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAsignacionesKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "por favor agregar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_txtAsignacionesKeyTyped

    private void txtParcialesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParcialesKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "por favor agregar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_txtParcialesKeyTyped

    private void txtExamenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExamenKeyTyped
        char numeros = evt.getKeyChar();
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "por favor agregar numeros");
            evt.consume();
        }
    }//GEN-LAST:event_txtExamenKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SistemaNotaGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnResetear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plOperaciones;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JTextField txtAsignaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtExamen;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtParciales;
    private javax.swing.JTextField txtPracticas;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
